import logging
import time

from inference import inference

large_csv_path = '../CPI_TrainSet/large_data.csv'

with open(large_csv_path, 'r') as fh:
    content = [line.strip() for line in list(fh)[:1000]]
testset = []
protein = 'MEPPTVPSERSLSLSLPGPREGQATLKPPPQHLWRQPRTPIRIQQRGYSDSAERAERERQPHRPIERADAMDTSDRPGLRTTRMSWPSSFHGTGTGSGGAGGGSSRRFEAENGPTPSPGRSPLDSQASPGLVLHAGAATSQRRESFLYRSDSDYDMSPKTMSRNSSVTSEAHAEDLIVTPFAQVLASLRSVRSNFSLLTNVPVPSNKRSPLGGPTPVCKATLSEETCQQLARETLEELDWCLEQLETMQTYRSVSEMASHKFKRMLNRELTHLSEMSRSGNQVSEYISTTFLDKQNEVEIPSPTMKEREKQQAPRPRPSQPPPPPVPHLQPMSQITGLKKLMHSNSLNNSNIPRFGVKTDQEELLAQELENLNKWGLNIFCVSDYAGGRSLTCIMYMIFQERDLLKKFRIPVDTMVTYMLTLEDHYHADVAYHNSLHAADVLQSTHVLLATPALDAVFTDLEILAALFAAAIHDVDHPGVSNQFLINTNSELALMYNDESVLENHHLAVGFKLLQEDNCDIFQNLSKRQRQSLRKMVIDMVLATDMSKHMTLLADLKTMVETKKVTSSGVLLLDNYSDRIQVLRNMVHCADLSNPTKPLELYRQWTDRIMAEFFQQGDRERERGMEISPMCDKHTASVEKSQVGFIDYIVHPLWETWADLVHPDAQEILDTLEDNRDWYYSAIRQSPSPPPEEESRGPGHPPLPDKFQFELTLEEEEEEEISMAQIPCTAQEALTAQGLSGVEEALDATIAWEASPAQESLEVMAQEASLEAELEAVYLTQQAQSTGSAPVAPDEFSSREEFVVAVSHSSPSALALQSPLLPAWRTLSVSEHAPGLPGLPSTAAEVEAQREHQAAKRACSACAGTFGEDTSALPAPGGGGSGIGDPT' # noqa

for data in content:
    molecule, _, label = data.split(',')
    testset.append([molecule, protein])


if __name__ == '__main__':
    logging.basicConfig(
        level=logging.INFO,
        format='[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s') # noqa
    print('result of easy test:', inference('c1ccccc1', 'MRGARGAWDFLCVLLLLLR'))
    print('pass the easy test, start batch test')
    start = time.time()
    for molecule, protein in testset:
        if len(protein) > 1000:
            protein = protein[:1000]
        inference(molecule, protein)
    print('Time Cost: %.2f second' % (time.time()-start))
    print('Finish Batch Test')
